[package]
name = "nandtetris-vm"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more.workspace = true
nandtetris-shared = {path = "../nandtetris-shared"}

[dev-dependencies]
pretty_assertions.workspace = true
