[workspace]
resolver = "2"

members = [
    "nandtetris-assembler",
    "nandtetris-shared",
    "nandtetris-vm",
]

[workspace.dependencies]
derive_more = {version = "1.0.0", features = ["from_str"]}
pretty_assertions = "1.4.1"
